apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tf-web-whatsapp-contact-data
  labels:
    app.kubernetes.io/name: tf-web-whatsapp-contact
    app.kubernetes.io/part-of: tf-web-whatsapp-contact
    app.kubernetes.io/environment: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-topology-alltype
  resources:
    requests:
      # Alibaba Cloud disks provisioned by this StorageClass require at least 20Gi.
      storage: 20Gi
