apiVersion: v1
kind: Service
metadata:
  name: tf-web-whatsapp-contact
  labels:
    app.kubernetes.io/name: tf-web-whatsapp-contact
    app.kubernetes.io/part-of: tf-web-whatsapp-contact
    app.kubernetes.io/environment: prod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tf-web-whatsapp-contact
  ports:
    - name: http
      port: 8003
      targetPort: http
